/** Title, author, category — 111 rows. Categories match API filter set. */
export const BOOK_TRIPLES = [
  ["Atomic Habits", "James Clear", "Self Help"],
  ["Deep Work", "Cal Newport", "Business"],
  ["Clean Code", "Robert C. Martin", "Programming"],
  ["The Psychology of Money", "Morgan Housel", "Psychology"],
  ["Rich Dad Poor Dad", "Robert Kiyosaki", "Business"],
  ["Sapiens", "Yuval Noah Harari", "History"],
  ["Think and Grow Rich", "Napoleon Hill", "Self Help"],
  ["JavaScript: The Good Parts", "Douglas Crockford", "Programming"],
  ["The Pragmatic Programmer", "David Thomas", "Programming"],
  ["Design Patterns", "Gang of Four", "Programming"],
  ["Educated", "Tara Westover", "Biography"],
  ["Becoming", "Michelle Obama", "Biography"],
  ["Steve Jobs", "Walter Isaacson", "Biography"],
  ["The Lean Startup", "Eric Ries", "Business"],
  ["Zero to One", "Peter Thiel", "Business"],
  ["Thinking, Fast and Slow", "Daniel Kahneman", "Psychology"],
  ["Man's Search for Meaning", "Viktor Frankl", "Psychology"],
  ["The Body Keeps the Score", "Bessel van der Kolk", "Psychology"],
  ["A Brief History of Time", "Stephen Hawking", "Science"],
  ["The Immortal Life of Henrietta Lacks", "Rebecca Skloot", "Science"],
  ["The Gene", "Siddhartha Mukherjee", "Science"],
  ["Guns, Germs, and Steel", "Jared Diamond", "History"],
  ["1776", "David McCullough", "History"],
  ["The Splendid and the Vile", "Erik Larson", "History"],
  ["Dune", "Frank Herbert", "Fiction"],
  ["Project Hail Mary", "Andy Weir", "Fiction"],
  ["The Nightingale", "Kristin Hannah", "Fiction"],
  ["Circe", "Madeline Miller", "Fiction"],
  ["The Seven Husbands of Evelyn Hugo", "Taylor Jenkins Reid", "Fiction"],
  ["The Midnight Library", "Matt Haig", "Fiction"],
  ["Klara and the Sun", "Kazuo Ishiguro", "Fiction"],
  ["Where the Crawdads Sing", "Delia Owens", "Fiction"],
  ["The Silent Patient", "Alex Michaelides", "Fiction"],
  ["It Ends with Us", "Colleen Hoover", "Fiction"],
  ["Normal People", "Sally Rooney", "Fiction"],
  ["A Man Called Ove", "Fredrik Backman", "Fiction"],
  ["The Song of Achilles", "Madeline Miller", "Fiction"],
  ["Outliers", "Malcolm Gladwell", "Business"],
  ["Drive", "Daniel H. Pink", "Business"],
  ["Never Split the Difference", "Chris Voss", "Business"],
  ["Influence", "Robert Cialdini", "Psychology"],
  ["Grit", "Angela Duckworth", "Self Help"],
  ["The Power of Habit", "Charles Duhigg", "Self Help"],
  ["Can't Hurt Me", "David Goggins", "Self Help"],
  ["Make Your Bed", "William McRaven", "Self Help"],
  ["Essentialism", "Greg McKeown", "Self Help"],
  ["The War of Art", "Steven Pressfield", "Self Help"],
  ["Hooked", "Nir Eyal", "Tech"],
  ["The Innovator's Dilemma", "Clayton Christensen", "Tech"],
  ["The Phoenix Project", "Gene Kim", "Tech"],
  ["Building a Second Brain", "Tiago Forte", "Tech"],
  ["Code Complete", "Steve McConnell", "Programming"],
  ["You Don't Know JS", "Kyle Simpson", "Programming"],
  ["Eloquent JavaScript", "Marijn Haverbeke", "Programming"],
  ["The Mythical Man-Month", "Frederick Brooks", "Programming"],
  ["JavaScript Mastery", "Chris North", "Programming"],
  ["To Kill a Mockingbird", "Harper Lee", "Fiction"],
  ["1984", "George Orwell", "Fiction"],
  ["Pride and Prejudice", "Jane Austen", "Fiction"],
  ["The Great Gatsby", "F. Scott Fitzgerald", "Fiction"],
  ["Crime and Punishment", "Fyodor Dostoevsky", "Fiction"],
  ["The Lord of the Rings", "J.R.R. Tolkien", "Fiction"],
  ["Harry Potter and the Sorcerer's Stone", "J.K. Rowling", "Fiction"],
  ["The Hobbit", "J.R.R. Tolkien", "Fiction"],
  ["Jane Eyre", "Charlotte Bronte", "Fiction"],
  ["Wuthering Heights", "Emily Bronte", "Fiction"],
  ["The Catcher in the Rye", "J.D. Salinger", "Fiction"],
  ["Brave New World", "Aldous Huxley", "Fiction"],
  ["The Handmaid's Tale", "Margaret Atwood", "Fiction"],
  ["The Alchemist", "Paulo Coelho", "Fiction"],
  ["Life of Pi", "Yann Martel", "Fiction"],
  ["The Book Thief", "Markus Zusak", "Fiction"],
  ["All the Light We Cannot See", "Anthony Doerr", "Fiction"],
  ["A Little Life", "Hanya Yanagihara", "Fiction"],
  ["The Goldfinch", "Donna Tartt", "Fiction"],
  ["Gone Girl", "Gillian Flynn", "Fiction"],
  ["Big Little Lies", "Liane Moriarty", "Fiction"],
  ["The Girl with the Dragon Tattoo", "Stieg Larsson", "Fiction"],
  ["The Kite Runner", "Khaled Hosseini", "Fiction"],
  ["A Thousand Splendid Suns", "Khaled Hosseini", "Fiction"],
  ["Good Calories, Bad Calories", "Gary Taubes", "Science"],
  ["The Emperor of All Maladies", "Siddhartha Mukherjee", "Science"],
  ["Astrophysics for People in a Hurry", "Neil deGrasse Tyson", "Science"],
  ["Cosmos", "Carl Sagan", "Science"],
  ["The Selfish Gene", "Richard Dawkins", "Science"],
  ["A Short History of Nearly Everything", "Bill Bryson", "Science"],
  ["The Sixth Extinction", "Elizabeth Kolbert", "Science"],
  ["Silent Spring", "Rachel Carson", "Science"],
  ["The Man Who Mistook His Wife for a Hat", "Oliver Sacks", "Science"],
  ["When Breath Becomes Air", "Paul Kalanithi", "Biography"],
  ["Shoe Dog", "Phil Knight", "Biography"],
  ["The Autobiography of Malcolm X", "Malcolm X and Alex Haley", "Biography"],
  ["Open", "Andre Agassi", "Biography"],
  ["Greenlights", "Matthew McConaughey", "Biography"],
  ["Born a Crime", "Trevor Noah", "Biography"],
  ["The Wright Brothers", "David McCullough", "Biography"],
  ["Leonardo da Vinci", "Walter Isaacson", "Biography"],
  ["Benjamin Franklin", "Walter Isaacson", "Biography"],
  ["Einstein", "Walter Isaacson", "Biography"],
  ["Team of Rivals", "Doris Kearns Goodwin", "History"],
  ["Salt", "Mark Kurlansky", "History"],
  ["Forgotten Ally", "Rana Mitter", "History"],
  ["The Guns of August", "Barbara Tuchman", "History"],
  ["The Warmth of Other Suns", "Isabel Wilkerson", "History"],
  ["Caste", "Isabel Wilkerson", "History"],
  ["The Light We Lost", "Jill Santopolo", "Story"],
  ["One Day in December", "Josie Silver", "Story"],
  ["The Paper Palace", "Miranda Cowley Heller", "Story"],
  ["The Rose Code", "Kate Quinn", "Story"],
  ["The Diamond Eye", "Kate Quinn", "Story"],
  ["The Dictionary of Lost Words", "Pip Williams", "Story"],
];
